# Generated by Django 3.1.1 on 2021-07-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('city', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weather_description', models.CharField(max_length=200, null=True)),
                ('temperature', models.FloatField(default=0, null=True)),
                ('pressure', models.FloatField(default=0, null=True)),
                ('humidity', models.FloatField(default=0, null=True)),
                ('wind_speed', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
